# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-06 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='thyroidNoduleStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MRN', models.CharField(default='', max_length=20)),
                ('accession', models.CharField(default='', max_length=20)),
                ('datetimeEntry', models.DateTimeField(default=datetime.datetime.now)),
                ('Nodule1', models.BooleanField(default=False)),
                ('Nodule1_location1', models.CharField(default='', max_length=20)),
                ('Nodule1_location2', models.CharField(default='', max_length=20)),
                ('Nodule1_location3', models.CharField(default='', max_length=20)),
                ('Nodule1_location4', models.CharField(default='', max_length=20)),
                ('Nodule1_sizeX', models.IntegerField(default=0)),
                ('Nodule1_sizeY', models.IntegerField(default=0)),
                ('Nodule1_sizeZ', models.IntegerField(default=0)),
                ('Nodule1_composition', models.IntegerField(default=10)),
                ('Nodule1_echogenicity', models.IntegerField(default=10)),
                ('Nodule1_shape', models.IntegerField(default=10)),
                ('Nodule1_margin', models.IntegerField(default=10)),
                ('Nodule1_cometTail', models.BooleanField(default=False)),
                ('Nodule1_macroCalcification', models.BooleanField(default=False)),
                ('Nodule1_rimCalcification', models.BooleanField(default=False)),
                ('Nodule1_punctateCalcification', models.BooleanField(default=False)),
                ('Nodule1_recScore', models.IntegerField(default=0)),
                ('Nodule2', models.BooleanField(default=False)),
                ('Nodule2_location1', models.CharField(default='', max_length=20)),
                ('Nodule2_location2', models.CharField(default='', max_length=20)),
                ('Nodule2_location3', models.CharField(default='', max_length=20)),
                ('Nodule2_location4', models.CharField(default='', max_length=20)),
                ('Nodule2_sizeX', models.IntegerField(default=0)),
                ('Nodule2_sizeY', models.IntegerField(default=0)),
                ('Nodule2_sizeZ', models.IntegerField(default=0)),
                ('Nodule2_composition', models.IntegerField(default=10)),
                ('Nodule2_echogenicity', models.IntegerField(default=10)),
                ('Nodule2_shape', models.IntegerField(default=10)),
                ('Nodule2_margin', models.IntegerField(default=10)),
                ('Nodule2_cometTail', models.BooleanField(default=False)),
                ('Nodule2_macroCalcification', models.BooleanField(default=False)),
                ('Nodule2_rimCalcification', models.BooleanField(default=False)),
                ('Nodule2_punctateCalcification', models.BooleanField(default=False)),
                ('Nodule2_recScore', models.IntegerField(default=0)),
                ('Nodule3', models.BooleanField(default=False)),
                ('Nodule3_location1', models.CharField(default='', max_length=20)),
                ('Nodule3_location2', models.CharField(default='', max_length=20)),
                ('Nodule3_location3', models.CharField(default='', max_length=20)),
                ('Nodule3_location4', models.CharField(default='', max_length=20)),
                ('Nodule3_sizeX', models.IntegerField(default=0)),
                ('Nodule3_sizeY', models.IntegerField(default=0)),
                ('Nodule3_sizeZ', models.IntegerField(default=0)),
                ('Nodule3_composition', models.IntegerField(default=10)),
                ('Nodule3_echogenicity', models.IntegerField(default=10)),
                ('Nodule3_shape', models.IntegerField(default=10)),
                ('Nodule3_margin', models.IntegerField(default=10)),
                ('Nodule3_cometTail', models.BooleanField(default=False)),
                ('Nodule3_macroCalcification', models.BooleanField(default=False)),
                ('Nodule3_rimCalcification', models.BooleanField(default=False)),
                ('Nodule3_punctateCalcification', models.BooleanField(default=False)),
                ('Nodule3_recScore', models.IntegerField(default=0)),
                ('Nodule4', models.BooleanField(default=False)),
                ('Nodule4_location1', models.CharField(default='', max_length=20)),
                ('Nodule4_location2', models.CharField(default='', max_length=20)),
                ('Nodule4_location3', models.CharField(default='', max_length=20)),
                ('Nodule4_location4', models.CharField(default='', max_length=20)),
                ('Nodule4_sizeX', models.IntegerField(default=0)),
                ('Nodule4_sizeY', models.IntegerField(default=0)),
                ('Nodule4_sizeZ', models.IntegerField(default=0)),
                ('Nodule4_composition', models.IntegerField(default=10)),
                ('Nodule4_echogenicity', models.IntegerField(default=10)),
                ('Nodule4_shape', models.IntegerField(default=10)),
                ('Nodule4_margin', models.IntegerField(default=10)),
                ('Nodule4_cometTail', models.BooleanField(default=False)),
                ('Nodule4_macroCalcification', models.BooleanField(default=False)),
                ('Nodule4_rimCalcification', models.BooleanField(default=False)),
                ('Nodule4_punctateCalcification', models.BooleanField(default=False)),
                ('Nodule4_recScore', models.IntegerField(default=0)),
            ],
        ),
    ]
