# Generated by Django 2.0.9 on 2019-02-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIRADSapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thyroidnodulestudy',
            name='utswId',
            field=models.CharField(default='', max_length=20),
        ),
    ]
